-- Create Profiles Table (Public Profile Data)
create table profiles (
  id uuid references auth.users not null primary key,
  weight numeric,
  height numeric,
  bike_type text,
  crank_length numeric,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable RLS for Profiles
alter table profiles enable row level security;

create policy "Users can view their own profile" on profiles
  for select using (auth.uid() = id);

create policy "Users can update their own profile" on profiles
  for update using (auth.uid() = id);

create policy "Users can insert their own profile" on profiles
  for insert with check (auth.uid() = id);

-- Create Rides Table (History)
create table rides (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  date timestamp with time zone default timezone('utc'::text, now()),
  duration numeric,
  avg_power numeric,
  avg_speed numeric,
  data_points jsonb,
  workout_name text
);

-- Enable RLS for Rides
alter table rides enable row level security;

create policy "Users can view their own rides" on rides
  for select using (auth.uid() = user_id);

create policy "Users can insert their own rides" on rides
  for insert with check (auth.uid() = user_id);

-- Create Achievements Table
create table user_achievements (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  achievement_id text not null,
  unlocked_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable RLS for Achievements
alter table user_achievements enable row level security;

create policy "Users can view their own achievements" on user_achievements
  for select using (auth.uid() = user_id);

create policy "Users can insert their own achievements" on user_achievements
  for insert with check (auth.uid() = user_id);

-- Create Custom Workouts Table
create table custom_workouts (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  title text,
  description text,
  intervals jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable RLS for Custom Workouts
alter table custom_workouts enable row level security;

create policy "Users can view their own workouts" on custom_workouts
  for select using (auth.uid() = user_id);

create policy "Users can insert their own workouts" on custom_workouts
  for insert with check (auth.uid() = user_id);
